#!/usr/bin/env bun

import { $ } from "bun"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const opencodeDir = path.resolve(__dirname, "..")
const appDir = path.resolve(opencodeDir, "../app")
const dist = path.join(appDir, "dist")
const sharedDir = path.join(opencodeDir, "src/server/shared")
const manifestPath = path.join(sharedDir, "web-ui-manifest.gen.ts")

const skipBuild = process.argv.includes("--skip-build")
const onlyBuild = process.argv.includes("--only-build")

async function buildFrontend() {
  console.log("Building frontend (packages/app)…")
  await $`bun run --cwd ${appDir} build`
}

async function generateManifest() {
  const files = (await Array.fromAsync(new Bun.Glob("**/*").scan({ cwd: dist })))
    .map((file) => file.replaceAll("\\", "/"))
    .filter((file) => !file.endsWith(".map"))
    .sort()

  if (files.length === 0) {
    throw new Error(`No files found in ${dist}. Did the frontend build succeed?`)
  }

  const rel = path.relative(sharedDir, dist).replaceAll("\\", "/")
  const imports = files.map(
    (file, i) => `import file_${i} from ${JSON.stringify(`${rel}/${file}`)} with { type: "file" };`,
  )
  const entries = files.map((file, i) => `  ${JSON.stringify(file)}: file_${i},`)

  const output = [
    "// AUTO-GENERATED by script/build-web.ts — do not edit or commit.",
    "// Maps built asset URLs to their on-disk paths so the backend can serve",
    "// an embedded web UI from a single process/port.",
    ...imports,
    "export default {",
    ...entries,
    "} as const satisfies Record<string, string>",
    "",
  ].join("\n")

  await Bun.write(manifestPath, output)
  console.log(`Wrote manifest → ${path.relative(process.cwd(), manifestPath)} (${files.length} files)`)
}

if (onlyBuild) {
  await buildFrontend()
} else if (skipBuild) {
  await generateManifest()
} else {
  await buildFrontend()
  await generateManifest()
}
